import React from "react";
import {StyleSheet} from "react-native";

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    mainHeaderContainer: {
         backgroundColor: "#222423",
         height: 100,
         paddingTop: 55,
         alignItems: "center",
    },
    mainHeaderText: {
        fontFamily: "Rockwell",
        color: "#fff",
        fontSize: 24,
        textAlign: "center",
        fontWeight: "bold",
        paddingTop: 10,
        textShadowColor: "#2bad4e",
        textShadowOffset: {width: -1, height: 1},
        textShadowRadius: 10,
    },
    playerBox: {
        backgroundColor: "#2bad4e",
        marginVertical: 0,
        marginTop: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 1,
        borderStyle: "dashed",
        borderWidth: .5,
        borderColor: "#2f3030",
        flexDirection: "row",
        justifyContent: "space-between",
        padding: 25,
    },
    playerText: {
        color: "#fff",
        fontWeight: "bold",
        paddingTop: 10,
        textAlign: "center",
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: {width: -1, height: 1},
        textShadowRadius: 10,
        marginLeft: 8,
        fontSize: 16,
},
    playerScoreText: {
        color: "#fff",
        fontWeight: "bold",
        padding: 10,
        fontSize: 45,
        textAlign: "center",
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: {width: -1, height: 1},
        textShadowRadius: 10,
        left: -10,
    },
    playerBoxAdd: {
        marginRight: 15,
        fontWeight: "bold",
        color: "#fff",
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: {width: -1, height: 1},
        textShadowRadius: 10,
        marginTop: 15,
        fontSize: 35,
    },
    playerNameEdit: {
      color: "#fff",
        padding: 0,
        margin: 0,
        right: -5,
    },
    playerNameBox: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    modalScoreBox: {
        backgroundColor: "#222423",
        flex: .58,
        width: 335,
        alignSelf: "center",
        marginTop: 120,
        opacity: .97,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 1,
        borderStyle: "dashed",
        borderWidth: .5,
        borderColor: "#fff",
        borderRadius: 900,
    },
    modalHeader: {
        color: "#fff",
        textAlign: "center",
        textAlignVertical: "top",
        marginTop: 20,
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: {width: -1, height: 1},
        textShadowRadius: 10,
        fontWeight: "bold",
        fontSize: 16,
    },
    modalTextInput: {
        borderStyle: "dashed",
        backgroundColor: "#fff",
        borderColor: "#fff",
        color: "#333",
        alignSelf: "center",
        marginTop: 20,
        fontSize: 30,
        width: 215,
        textAlign: "center",
        borderWidth: 1,
        height: 65,
        fontWeight: "bold",
    },
    bullseye: {
        color: "red",
        fontSize: 24,
        textAlign: "center",
        marginTop: 15,
        borderStyle: "dashed",
        borderWidth: 1,
        borderColor: "#fff",
        borderRadius: 100,
        fontWeight: "bold",
        height: 40,
        paddingTop: 3,
        textShadowColor: "red",
        textShadowOffset: {width: -1, height: 1},
        textShadowRadius: 10,
        shadowColor: "#fff",
        shadowRadius: 10,
    },
    multiplierBox: {
        flexDirection: "row",
        justifyContent: "center",
    },
    multiplierButton: {
        padding: 15,
        marginLeft: 5,
        marginRight: 5,
        marginTop: 30,
        borderStyle: "dashed",
        borderWidth: 1,
        color: "#d45617",
        fontWeight: "bold",
        fontSize: 18,
        borderColor: "#fff",
        maxWidth: 95,
        borderRadius: 20,
    },
    modalExit: {
        marginLeft: 240,
        color: "#fff",
        padding: 0,
    },
    modalHeaderBox: {

    }
});

export default styles;